OVERRIDE_ALLOWED = [
    'ACLOVERRIDE',
    'ACL_OVERRIDE_HASH',
    'DIFF_VERIFY_OVERRIDE',
    'PCLOVERRIDE',
    'PCVALIDATIONOVERRIDE',
    'TRUNKBLOCKERFIX',
    'EOLVALIDATIONOVERRIDE',
    'CHERRYPICKOVERRIDE',
]
